# Generated by Django 5.2 on 2026-10-05 12:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recruitment", "0005_tighten_applicant_sid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="作业要求、需提交的材料等",
                        verbose_name="说明",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="doclib/assignments/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                        verbose_name="作业文件（PDF）",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="截止时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="recruitment.batch",
                        verbose_name="招新批次",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        blank=True,
                        help_text="保存时自动创建/复用（round_type=homework），用于批改录分",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="recruitment.round",
                        verbose_name="关联轮次",
                    ),
                ),
            ],
            options={
                "verbose_name": "作业",
                "verbose_name_plural": "作业",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("guide", "导学材料"),
                            ("homework", "作业文件"),
                            ("appendix", "附录"),
                            ("other", "其他"),
                        ],
                        default="guide",
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                (
                    "file",
                    models.FileField(
                        upload_to="doclib/documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "zip"]
                            )
                        ],
                        verbose_name="文件（PDF 或 ZIP）",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传人",
                    ),
                ),
            ],
            options={
                "verbose_name": "资料文档",
                "verbose_name_plural": "资料文档",
                "ordering": ["category", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=20, verbose_name="学号")),
                ("name", models.CharField(max_length=30, verbose_name="姓名")),
                (
                    "report",
                    models.FileField(
                        upload_to="doclib/submissions/report/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                        verbose_name="报告（PDF）",
                    ),
                ),
                (
                    "source",
                    models.FileField(
                        upload_to="doclib/submissions/source/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["zip"])
                        ],
                        verbose_name="源代码（ZIP）",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        blank=True,
                        help_text="提交时按学号+姓名匹配报名库自动关联，用于批改录分",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="recruitment.applicant",
                        verbose_name="报名者",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="doclib.assignment",
                        verbose_name="作业",
                    ),
                ),
            ],
            options={
                "verbose_name": "作业提交",
                "verbose_name_plural": "作业提交",
                "ordering": ["-submitted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assignment", "student_id"),
                        name="unique_assignment_student",
                    )
                ],
            },
        ),
    ]
