# Generated by Django 5.2 on 2026-09-30 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="批次名称")),
                (
                    "signup_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="报名开始时间"
                    ),
                ),
                (
                    "signup_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="报名截止时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "未开始"),
                            ("open", "报名中"),
                            ("training", "培训中"),
                            ("assessing", "考核中"),
                            ("closed", "已结束"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="说明")),
            ],
            options={
                "verbose_name": "招新批次",
                "verbose_name_plural": "招新批次",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="姓名")),
                (
                    "student_id",
                    models.CharField(max_length=20, unique=True, verbose_name="学号"),
                ),
                (
                    "grade",
                    models.CharField(
                        help_text="如：2026", max_length=10, verbose_name="年级"
                    ),
                ),
                ("major", models.CharField(max_length=50, verbose_name="专业")),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="联系方式"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("signed", "已报名"),
                            ("training", "培训中"),
                            ("passed", "通过"),
                            ("failed", "淘汰"),
                            ("waitlist", "候补"),
                        ],
                        default="signed",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "signup_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="报名时间"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicants",
                        to="recruitment.batch",
                        verbose_name="批次",
                    ),
                ),
            ],
            options={
                "verbose_name": "报名者",
                "verbose_name_plural": "报名者",
                "ordering": ["-signup_time"],
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="轮次名称")),
                (
                    "round_type",
                    models.CharField(
                        choices=[
                            ("training", "培训"),
                            ("assessment", "考核"),
                            ("homework", "作业"),
                        ],
                        default="training",
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="日期")),
                ("note", models.TextField(blank=True, verbose_name="说明")),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="recruitment.batch",
                        verbose_name="批次",
                    ),
                ),
            ],
            options={
                "verbose_name": "考核轮次",
                "verbose_name_plural": "考核轮次",
                "ordering": ["batch", "id"],
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A", "A"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B", "B"),
                            ("B-", "B-"),
                        ],
                        max_length=2,
                        verbose_name="等级",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="验收人员的文本评价，可选",
                        verbose_name="评价",
                    ),
                ),
                (
                    "entered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="录入时间"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="recruitment.applicant",
                        verbose_name="报名者",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="录入人",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="recruitment.round",
                        verbose_name="轮次",
                    ),
                ),
            ],
            options={
                "verbose_name": "成绩",
                "verbose_name_plural": "成绩",
                "ordering": ["applicant", "round"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("applicant", "round"), name="unique_applicant_round"
                    )
                ],
            },
        ),
    ]
