# Generated by Django 5.2 on 2026-10-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0002_create_recruit_admin_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="sid",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="学生编号"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="grade",
            field=models.CharField(max_length=10, verbose_name="年级"),
        ),
    ]
