# Generated by Django 5.2 on 2026-10-01 07:17
# T3-0：0004 已回填 sid=1..N，此处收紧为非空 + 唯一（无 default，因无 NULL 残留）。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0004_backfill_applicant_sid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="sid",
            field=models.PositiveIntegerField(unique=True, verbose_name="学生编号"),
        ),
    ]
