# Generated by Django 5.2 on 2026-10-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0005_tighten_applicant_sid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="contact",
            field=models.CharField(
                help_text="必填，保证消息通畅", max_length=50, verbose_name="QQ号"
            ),
        ),
    ]
