# Generated by Django 5.2 on 2026-09-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slogan",
                    models.CharField(
                        blank=True,
                        help_text="主页 hero 展示的一句话标语",
                        max_length=100,
                        verbose_name="口号",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        help_text="概况页全文，主页摘要自动截断", verbose_name="简介"
                    ),
                ),
                (
                    "founded_year",
                    models.PositiveIntegerField(default=2017, verbose_name="成立年份"),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        help_text="QQ群 / 邮箱等，展示于页脚与概况页",
                        max_length=200,
                        verbose_name="联系方式",
                    ),
                ),
            ],
            options={
                "verbose_name": "实验室概况",
                "verbose_name_plural": "实验室概况",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="如：教授 / 副教授 / 硕导",
                        max_length=100,
                        verbose_name="头衔",
                    ),
                ),
                (
                    "research",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="研究方向"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="简介")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="teachers/",
                        verbose_name="照片",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="越小越靠前", verbose_name="排序"
                    ),
                ),
            ],
            options={
                "verbose_name": "指导老师",
                "verbose_name_plural": "指导老师",
                "ordering": ["order", "id"],
            },
        ),
    ]
