# Generated by Django 5.2 on 2026-10-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labprofile",
            name="competitions",
            field=models.TextField(
                blank=True, help_text="每行一条", verbose_name="参与竞赛"
            ),
        ),
        migrations.AddField(
            model_name="labprofile",
            name="equipment",
            field=models.TextField(
                blank=True, help_text="每行一条", verbose_name="设备配置"
            ),
        ),
        migrations.AddField(
            model_name="labprofile",
            name="knowledge",
            field=models.TextField(
                blank=True, help_text="每行一条", verbose_name="可学知识"
            ),
        ),
        migrations.AddField(
            model_name="labprofile",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="如：计算机中心楼 302B、310、311",
                max_length=200,
                verbose_name="实验室地点",
            ),
        ),
        migrations.AddField(
            model_name="labprofile",
            name="media_accounts",
            field=models.TextField(
                blank=True, help_text="B站/抖音等，每行一条", verbose_name="新媒体账号"
            ),
        ),
        migrations.AddField(
            model_name="labprofile",
            name="works",
            field=models.TextField(
                blank=True, help_text="每行一条", verbose_name="已有作品"
            ),
        ),
    ]
